version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: blogcms-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: blogcms

  api:
    build: .
    container_name: blogcms-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/blogcms
    command: ["node", "app.js"]

volumes:
  mongo_data:
